sudo: false

language: android

jdk:
  - openjdk11
  
android:
  components:
      - platform-tools
      - tools
      - build-tools-29.0.3
      - android-30

      - extra-google-google_play_services
      - extra-google-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-30"

before_script:
  - echo 'storePassword=xxx' >  keystore.properties
  - echo 'keyPassword=xxx' >> keystore.properties
  - echo 'keyAlias=xxx' >>  keystore.properties
  - echo 'storeFile=xxx' >> keystore.properties

script:
  - ./gradlew clean lint detekt compileDebugSources test
