sudo: false
language: android
android:
  components:
      - tools
      - platform-tools
      - tools

      - build-tools-26.0.2
      - android-26

      - extra-google-google_play_services
      - extra-google-m2repository

script:
  - ./gradlew clean build testDebugUnitTest