sudo: false

language: android

android:
  components:
      - tools
      - platform-tools
      - tools
      - build-tools-29.0.0
      - build-tools-28.0.3
      - android-28
      - android-29

      - extra-google-google_play_services
      - extra-google-m2repository

before_script:
  - echo 'storePassword=xxx' >  keystore.properties
  - echo 'keyPassword=xxx' >> keystore.properties
  - echo 'keyAlias=xxx' >>  keystore.properties
  - echo 'storeFile=xxx' >> keystore.properties

script:
  - ./gradlew clean lint testDebugUnitTest
